name: KeepInventory
version: ${version}
author: nuoxian
main: org.earlydreamland.keepinventory.KeepInventory
api-version: 1.13

commands:
  kip:
    description: KeepInventory 插件主命令
    usage: /kip [reload|version]
    permission: keepinventory.use
    aliases: [keepinventory]
    tab-complete: true

permissions:
  keepinventory.use:
    description: 允许使用插件命令
    default: true
  keepinventory.reload:
    description: 允许重载插件配置
    default: op